### ISSUE TITLE
WinUSB need UEFI booting support

### ISSUE THREAD

**Issue by fpemud** [slacka/WinUSB#1]
My computer uses UEFI mode for booting.

When I'm using WinUSB, I encounters the following error:
fpemud-workstation / # winusb --format /cn_windows_7_ultimate_with_sp1_x86_dvd_u_677486.iso /dev/sde -v
Formating device...
Mounting...
mount: /dev/loop1 is write-protected, mounting read-only
Copying...
Installing grub...
grub2-install: error: /usr/lib/grub/x86_64-efi/modinfo.sh doesn't exist. Please specify --target or --directory.
Error occured !
Syncing...

After I install efi-64 support for grub, there's still an error:
fpemud-workstation garbage # winusb --format /media/garbage/root/pkg-garbage/fpemud-virtmanager-plugin-win7/files/win7/data/cn_windows_7_ultimate_with_sp1_x86_dvd_u_677486.iso /dev/sde -v
Formating device...
Mounting...
mount: /dev/loop2 is write-protected, mounting read-only
Copying...
Installing grub...
Installing for x86_64-efi platform.
grub2-install: error: /media/winusb_target_1430290241_13824 doesn't look like an EFI partition.
.
Error occured !
Syncing...

LiveUSB of many Linux distros support dual boot from legacy BIOS and UEFI, WinUSB needs this support too.

**Comment by fpemud** [comment]
reference:
http://askubuntu.com/questions/289559/how-can-i-create-a-windows-bootable-usb-stick-with-ubuntu

**Comment by Lin-Buo-Ren** [comment]
This issue is in fact not on UEFI booting support instead of making USBs on UEFI platform, the failing `grub-install` command's purpose is only on installing GRUB into USB's MBR(and MBR gap and modules), which is not related to UEFI booting afterall.

If you still concern about this issue please tryout the patch.

**Comment by Lin-Buo-Ren** [comment]
It seems that in fact WinUSB does, not supporting UEFI booting(I merely fixed the error message), please refer the newly created issue #15
