### ISSUE TITLE
[PPA] winusb package shouldn't depend on grub-pc

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [slacka/WinUSB#14]
I recently switched from grub-pc package to grub-efi package and notice that WinUSB is automatically removed during the process.

~~`grub-efi` package conflict with `grub-pc`, so users' using UEFI system can't install WinUSB and using it to create Windows installation media.~~
**UPDATE:** according to the control file winusb package is in fact depend on `grub-pc OR grub-efi` so it's no longer a problem here.

Instead winusb package should depend on grub-{pc/efi}-bin package, which provide all the required files to install PC/EFI GRUB bootloader

**Comment by slacka** [comment]
I'm not colingille and don't have access to his ppa. You could try emailing him. Let's keep this issue open for any future package maintainers.

**Comment by Lin-Buo-Ren** [comment]
I'm closing this as the situation is not really I've expected.
