### ISSUE TITLE
Set LANG="C" instead when running commands

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [slacka/WinUSB#20]
Currently `LANG` environmental variable is set to ""(empty string) when running commands.

According to GNU Gettext documentation(`$ info gettext "The LANGUAGE variable"`):

```
Note: The variable ‘LANGUAGE’ is ignored if the locale is set to ‘C’. In other words, you have to first enable localization, by setting ‘LANG’ (or ‘LC_ALL’) to a value other than ‘C’, before you can use a language priority list through the ‘LANGUAGE’ variable.
```

I believe setting to "C" is the proper way to disable localization.  Patches on the way...

**Comment by slacka** [comment]
Good catch. Thank you!
