### ISSUE TITLE
[Debian packaging]Depend on grub-pc-bin

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [slacka/WinUSB#22]
grub-pc-bin package is needed for EFI platform user to install PC/MBR style GRUB boot loader.

We'll also need to depend on grub-efi-bin after UEFI booting support is implemented in the future.

**Comment by slacka** [comment]
UEFI  support would be great. Have you tested this + a fat32 format?

**Comment by Lin-Buo-Ren** [comment]
@slacka 
> UEFI support would be great. Have you tested this + a fat32 format?

I did test it and it works as expected.
