### ISSUE TITLE
Permission denied while trying to copy a file

### ISSUE THREAD

**Issue by zoobab** [slacka/WinUSB#33]
Any idea why cp throws this error?

```
root@mybox# winusb --format win10.iso /dev/sdb
Formating device...
Mounting...
mount: /dev/loop3 is write-protected, mounting read-only
Copying...
cp: cannot create regular file '/media/winusb_target_1464780198_28657/./autorun.inf': Permission denied
Error occured !
Syncing...
Cleaning...
Umounting and removing '/media/winusb_iso_1464780198_28657'...
Umounting and removing '/media/winusb_target_1464780198_28657'...
```

**Comment by Lin-Buo-Ren** [comment]
Hi, it seems that you're using a old version, please use the latest revision on the master branch to verify this issue still available

**Comment by JonnyTech** [comment]
I have just used the latest from [Github](https://codeload.github.com/slacka/WinUSB/zip/master):

> sudo winusb --install /home/user/Downloads/Win10_1511_2_EnglishInternational_x64.iso /dev/sdb1
Mounting...
mount: /dev/loop0 is write-protected, mounting read-only
Copying...
cp: error reading './boot/en-gb/bootsect.exe.mui': Input/output error
Error occured!
Syncing...
Cleaning...
Unmounting and removing '/media/winusb_iso_1468247245_24258'...
Unmounting and removing '/media/winusb_target_1468247245_24258'...

**Comment by Lin-Buo-Ren** [comment]
@JonnyTech 
> cp: error reading './boot/en-gb/bootsect.exe.mui': Input/output error
It seems that your source media has error, please try another one to see if the problem persist.

**Comment by JonnyTech** [comment]
> It seems that your source media has error, please try another one to see if the problem persist.

You are indeed correct, many thanks, sorry for the noise.

**Comment by slacka** [comment]
Closing as invalid.
