### ISSUE TITLE
Wrong example

### ISSUE THREAD

**Issue by larsnystrom** [slacka/WinUSB#37]
When running `winusb` with no arguments, a usage example is showed:

    winusb usage
    Install a Windows ISO on an FAT partition and edit MBR of the device
      winusb --install <iso path> <partition>
      Example: winusb win7_amd64.iso /dev/sdd1

The example is wrong though, it should be

    Example: winusb win7_amd64.iso /dev/sdd

I.e. you shouldn't specify the partition, just the device (`/dev/sdd1` -> `/dev/sdd`). At least that's my experience, and also what [Web Upd8](http://www.webupd8.org/2016/06/make-bootable-windows-10-usb-install.html) says.

**Comment by Lin-Buo-Ren** [comment]
Hi, the command Web Upd8 mentions is rather the --format mode instead the --install mode.  Anyway I'll investigate this issue.

**Comment by Lin-Buo-Ren** [comment]
Hi, I've checked the code and verified that the &lt;partition&gt;(which correspond to $targetMedia in src/winusb) is indeed requires a partition block device (e.g. /dev/sdd1)

Using the block device of entire disk as &lt;partition&gt; seems also work as the script actually doesn't check this case but is not intended nor recommended.

**Comment by larsnystrom** [comment]
I'm sorry, I don't have time to reproduce this. I might have mixed up the commands but I don't think so. But if you can't reproduce it you can close this issue.

**Comment by Lin-Buo-Ren** [comment]
In fact there *is* something wrong about the command example: the mode switches (--install/--format) are missing.

However I believe the problem you've encountered when using `--install` mode against a partition device file is another cause.
