### ISSUE TITLE
grub install fails

### ISSUE THREAD

**Issue by djdeath** [slacka/WinUSB#38]
Trying to create a usb image with an image fails on my Debian (amd64) : 

```
$ sudo winusb --format image.iso /dev/sdb
Formatting device...
Wait 3 seconds for block device nodes to populate...
mkfs.fat 4.0 (2016-05-06)
mkfs.fat: warning - lowercase labels might not work properly with DOS or Windows
Mounting...
mount: /dev/loop0 is write-protected, mounting read-only
Copying...
Installing grub...
Installing for i386-pc platform.
grub-install: warning: Attempting to install GRUB to a disk with multiple partition labels.  This is not supported yet..
grub-install: warning: Embedding is not possible.  GRUB can only be installed in this setup by using blocklists.  However, blocklists are UNRELIABLE and their use is discouraged..
grub-install: error: will not proceed with blocklists.
Error occured!
Syncing...
```

The resulting image is not bootable.

**Comment by nhooyr** [comment]
http://askubuntu.com/questions/666527/install-grub-claims-that-i-have-multiple-partiton-labels-and-that-embedding-is

**Comment by Lin-Buo-Ren** [comment]
I can't reproduce this issue, what version of WinUSB you're using?

The installation of PC GRUB shouldn't cause problem as the `--format` mode entirely recreates the PC-compatible/MBR/msdos partition table and leave enough post-MBR gap for GRUB to embed

**Comment by Lin-Buo-Ren** [comment]
Also this issue might caused by the pre-existing partition table data structures, I recommend do a `# wipefs --all <target_device>` and retry

**Comment by osa1** [comment]
I'm having the same problem, and `wipefs` did not fix it for me.

**Comment by slacka** [comment]
Try this:

Assuming problem device is _/dev/sda_:

Create a new partition in the initial 1 MiB

```
$ parted /dev/sda
$ mkpart primary ext4 0MiB 1MiB
$ quit
```
Then, zero the newly created partition

`$ dd if=/dev/zero of=/dev/sda2
`
Then, delete the partition

```
$ parted /dev/sda
$ rm 2
$ quit
```

**Comment by osa1** [comment]
Yeah I'd already done that and it worked.

**Comment by osa1** [comment]
Maybe WinUSB should be doing that or at least mention this in the README or something :-)

**Comment by Lin-Buo-Ren** [comment]
This is rather a GRUB bug rather than WinUSB's, we may mention in the README but it shouldn't be "fixed" in our code.
