### ISSUE TITLE
Please support wxwidgets 3.x

### ISSUE THREAD

**Issue by Vitexus** [slacka/WinUSB#4]
Hallo. there is no clean way how to compile on current stable Debian.
Jessie drop wxwidgets-2.8 from its repository. 

This may help:
http://docs.wxwidgets.org/3.0/overview_changes_since28.html

Thank you

**Comment by bojs** [comment]
I have this problem too.

**Comment by Jeeppler** [comment]
I have this problem on Fedora too

**Comment by slacka** [comment]
mcirsta posted a fix. Please try the current master version.

**Comment by alishir** [comment]
I have this problem too.

**Comment by slacka** [comment]
With mcirsta's latest patch wxWidgets 3.0 works for me under Ubuntu.  Closing as FIXED.
