### ISSUE TITLE
Open file dialog should also show *.ISO (uppercase) files by default

### ISSUE THREAD

**Issue by fredg02** [slacka/WinUSB#40]
This is a minor UX bug, but I guess it's easy to fix. My workaround was to select "All files" to find my ISO file.

Thanks for keeping this tool alive!

**Comment by Lin-Buo-Ren** [comment]
Hi, I've made a patch to support the uppercase version file extension please [download](https://github.com/Lin-Buo-Ren/WinUSB/archive/issue-40-support-uppercase-extension.zip) and checkout if it's working.

**Comment by fredg02** [comment]
Thanks for fixing this and sorry for the late reply.
I'm pretty sure it's working now as intended. If you still want me to test it, let me know how, because the download link returns a 404.

**Comment by slacka** [comment]
This is an unofficial fork since the original project seems to be in limbo.

```
git clone https://github.com/slacka/WinUSB.git
sudo apt install libwxgtk3.0-dev 
./configure
make
sudo make install
```

**Comment by Lin-Buo-Ren** [comment]
@fredg02 Hi, the patch has been merged back to @slacka 's repo, you may try [this](https://github.com/slacka/WinUSB/archive/master.zip) if you like to.

**Comment by fredg02** [comment]
Works! Thanks for fixing this.
