### ISSUE TITLE
use grub2-install rather than grub-install

### ISSUE THREAD

**Issue by TheInitializer** [slacka/WinUSB#62]

**Comment by Vdragon** [comment]
`grub-install` is the command that existed in Debian-based distros(while I assumed that isn't following GRUB upstream's naming convention)

Maybe we could fix this by detecting which command is exist on the system.

**Comment by TheInitializer** [comment]
in Fedora grub-install doesn't work and only grub2-install exists

**Comment by Vdragon** [comment]
Add a few lines of command detection logic in the `src/winusb` Bash script should fix the problem, you may try patching yourself (and of course, send a PR)

**Comment by Lin-Buo-Ren** [comment]
The issue should be resolved since commit ec514a1a6
