### ISSUE TITLE
License Conflict Needs Resolving

### ISSUE THREAD

**Issue by MichaelTunnell** [slacka/WinUSB#73]
https://github.com/slacka/WinUSB/blob/master/COPYING displays GPL 3 where as https://github.com/slacka/WinUSB/blob/master/LICENSE shows the license as GPL 2.

This looks like the original license file that GitHub created by default just needs to be deleted to solve this issue.

**Comment by Lin-Buo-Ren** [comment]
Hi, thanks for reporting, should be fixed now.
