### ISSUE TITLE
Also try kdesudo in GUI

### ISSUE THREAD

**Issue by Parckwart** [slacka/WinUSB#78]
To gain superuser privilges, it might be a good idea to also try kdesudo besides gksudo. It's the same thing, just from KDE.

**Comment by shmohawk** [comment]
pkexec covers both, Fedora 25 doesn't have gksudo either.

**Comment by Lin-Buo-Ren** [comment]
Hello, since commit 94f1b08 the command used for privilege escalation has be replace by `pkexec`, as Policykit is in favor of *sudos this issue will be closed.
