### ISSUE TITLE
Unhelpful Error

### ISSUE THREAD

**Issue by dozyh** [slacka/WinUSB#80]
```
$ sudo winusb -v --format Downloads/en_windows_10_multiple_editions_version_1607_updated_jul_2016_x64_dvd_9058187/en_windows_10_multiple_editions_version_1607_updated_jul_2016_x64_dvd_9058187.iso /dev/sdf | tee winusb.log
Formatting device...
Wait 3 seconds for block device nodes to populate...
mkfs.fat: warning - lowercase labels might not work properly with DOS or Windows
mkfs.fat 3.0.27 (2014-11-12)
Mounting...
Copying...
Error occured!
Syncing...
Cleaning...
Unmounting and removing '/media/winusb_iso_1484310333_24645'...
Unmounting and removing '/media/winusb_target_1484310333_24645'...
```

Is there a way to get more useful output to diagnose this issue?

**Comment by Lin-Buo-Ren** [comment]
The error seems to be during the file copy process, which happens at <https://github.com/slacka/WinUSB/blob/master/src/winusb#L198>.

You may run winusb using `sudo bash -x $(which winusb) ...` to enable bash simple command tracing, refer GNU Bash Manual - Shell Builtin Commands - Modifying Shell Behavior - The Set Builtin for details

**Comment by dozyh** [comment]
I found that a different drive worked. That supports your theory that it's during the file copy.
