### ISSUE TITLE
How to install WinUSB on Fedora

### ISSUE THREAD

**Issue by timofonic** [slacka/WinUSB#81]
Hello.

I tried to build WinUSB on Fedora from source, but there's no make target. Am I missing something?

# git clone https://github.com/slacka/WinUSB.git
Cloning into 'WinUSB'...
remote: Counting objects: 376, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 376 (delta 0), reused 0 (delta 0), pack-reused 373
Receiving objects: 100% (376/376), 655.93 KiB | 332.00 KiB/s, done.
Resolving deltas: 100% (210/210), done.
Checking connectivity... done.
[root@timofonic src]# cd WinUSB/

# ./configure 
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for g++... no
checking for c++... no
checking for gpp... no
checking for aCC... no
checking for CC... no
checking for cxx... no
checking for cc++... no
checking for cl.exe... no
checking for FCC... no
checking for KCC... no
checking for RCC... no
checking for xlC_r... no
checking for xlC... no
checking whether the C++ compiler works... no
configure: error: in `/usr/src/WinUSB':
configure: error: C++ compiler cannot create executables
See `config.log' for more details

# make
make: *** No targets specified and no makefile found.  Stop.

**Comment by slacka** [comment]
If you had just googled your error, 

`error: C++ compiler cannot create executables `

Pretty much every results tells you what your problem is. You don't have a C++ compiler.
