### ISSUE TITLE
WinUSB on Fedora: Incorrect call to grub-install instead grub2-install

### ISSUE THREAD

**Issue by timofonic** [slacka/WinUSB#82]
Installing grub...
/usr/bin/winusb: line 402: grub-install: command not found
Error occured !
Syncing...
Cleaning...
Umounting and removing '/media/winusb_iso_1484430078_5249'...
Umounting and removing '/media/winusb_target_1484430078_5249'...

**Comment by timofonic** [comment]
I did ln -s to temporarily fix the "issue", but there are more issues...

Installing grub...
grub-install: error: /usr/lib/grub/x86_64-efi/modinfo.sh doesn't exist. Please specify --target or --directory.
Error occured !

**Comment by Lin-Buo-Ren** [comment]
Fedora support should be supported since commit ec514a1a (no need to symlink), make sure you are using the latest development revison(instead of the latest release)

Also the grub-install error also indicated that you're using an outdated version.

**Comment by timofonic** [comment]
It's the default FC25 grub, nothing else.

Thanks for your reply. I wonder if there'll be a new official release and 

Any plans to add non-windows features? Something like Sardu would be amazing, there's lack of a nice GUI tool like this for Linux.

**Comment by Lin-Buo-Ren** [comment]
Since this is a fork of a upstream-seems-not-want-to-maintain-project new releases are not likely happen until someone wants to take over the maintanence

**Comment by kawache** [comment]
hard fix : sudo ln -s /usr/sbin/grub2-install /usr/sbin/grub-install

**Comment by Lin-Buo-Ren** [comment]
This bug is already fixed a quite few releases before.

**Comment by kawache** [comment]
The bug occured for me on Fedora 27 yesterday,

I used this repo https://software.opensuse.org/package/winusb
