### ISSUE TITLE
WinUSB icon dont show after install

### ISSUE THREAD

**Issue by rquevedo** [slacka/WinUSB#85]
In Ubuntu 16.04 after install by generic method(because  dpkg-buildpackage -uc -b ends with this error "debian/rules:74: recipe for target 'binary-arch' failed") the icon to execute WinUSB dont show in ubuntu dash.

**Comment by Lin-Buo-Ren** [comment]
Thanks for the report, the dpkg-buildpackage failure issue should be fixed since commit b846c90b, please try the same method (the generic method could be reversed by executing `sudo make uninstall` from the source directory in terminal) if the issue still remains.

**Comment by rquevedo** [comment]
Thanks, the issue has been fixed. Only one thing, i cloned entire repo again because fails at first try, doing only a pull.
