### ISSUE TITLE
src/winusb code refactoring

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [slacka/WinUSB#87]
The main code, src/winusb, has several more-or-less annoying issues and possible improvements: 

* camelCaseNamingStyle variable names, which is conventional-wise not sane, could be renamed as underscore_separated_naming_style
* [Defensive BASH Programming](http://www.kfirlavi.com/blog/2012/11/14/defensive-bash-programming/), although may be unneeded, may more-or-less improve the code's maintainability and readability
* Most of the comments are incomprehensible/short/missing and can be improved for readability
    * Maybe [https://github.com/Anvil/bash-doxygen](bash-doxygen) would help?  This ain't a library though...
* Function and variable names can be expanded for readability in an expense of longer line.
* Command-line options can be expanded to longer version for readability in an expense of compatibility issues with older systems (which, can always be reverted afterwards if user encounters one)

These "improvements", which is mainly based on my preference may be unwise and inappropriate for others so this issue is opened for further discussion while I'm making the changes.

**Comment by slacka** [comment]
Defensive BASH Programming has some good ideas and cleaning up the comments are improvements everyone could benefit from. The others are exclusively a style issue. I have a slight preference no to change for change sake. But if it's important for you and makes the code more enjoyable to hack on, then go for it. 

It would be nice to hear something from @Congelli501 to know if this is just a temporary fork or if he's retired from the project for good.

**Comment by Lin-Buo-Ren** [comment]
Hello all, I've pushed a [temporary branch](https://github.com/slacka/WinUSB/tree/issue-87-code-refactoring) for the current progress on refactoring.

**Comment by Lin-Buo-Ren** [comment]
Hello all, the refactor process is finished and the code is quite stabilized, please test to see if there's any regression

**Comment by Lin-Buo-Ren** [comment]
Hello all, I've merged the refactor branch back to master on my end, I'll fix some issues that patch are available, if there's no objections I'll push the master branch to this repo.

**Comment by Lin-Buo-Ren** [comment]
The refactor branch has now been merged back to master.
