### ISSUE TITLE
Plans for a release?

### ISSUE THREAD

**Issue by bjornfor** [slacka/WinUSB#88]
When WinUSB is considered stable enough for end users, do you plan to tag a release?

(I just tested winusb CLI on git master and it successfully created a Windows USB stick for me. But I see there are some issues in github.)

I'd like to package WinUSB in Nix/Nixpkgs, but it feels wrong to just package a "random" commit.

**Comment by slacka** [comment]
If we're going to do a release, I we should do so in a way to not interfere with Congelli501's line.  Maybe 2.0?

@Lin-Buo-Ren Any thoughts?

**Comment by Lin-Buo-Ren** [comment]
I agree, and maybe a new package name, like winusb-slacka ?

林博仁 <Buo.Ren.Lin@gmail.com>

2017年2月5日 下午2:37，"slacka" <notifications@github.com>寫道：

**Comment by weberhofer** [comment]
It would be great to have a new release, I'd like to package it for openSUSE (https://build.opensuse.org/package/show/home:weberho:tools/winusb). I think there is no need to change the name of the package.

**Comment by Lin-Buo-Ren** [comment]
I'm just not convinced enough that bumping version alone will "not interfere" with @Congelli501 's further releases (if there's any)

**Comment by bjornfor** [comment]
So the package is stable enough for end users? Is the only thing missing deciding on a name and version number series?

**Comment by Lin-Buo-Ren** [comment]
Hello @bjornfor and other packagers that may be affected by this issue:

Aplogies for the long delay of fixing this issue, since now we've renamed the package from `winusb` to `winusb+` and released `v2.0.0` and so on, please update your packaging info to be align with us, thanks!

**Comment by Lin-Buo-Ren** [comment]
Also the application version has been changed to be smudged automatically using Git's path attribute filter feature, please run ./setup-development-environment.bash to smudge the name before building the software

**Comment by Lin-Buo-Ren** [comment]
Please note that the package name has (again) changed to `woeusb`, please refer #100 for details.

**Comment by bjornfor** [comment]
> Also the application version has been changed to be smudged automatically using Git's path attribute filter feature, please run ./setup-development-environment.bash to smudge the version before building the software

FYI, if ./setup-development-environment.bash isn't run, the version number "2.0.3" is used from the ./configure script that is shipped in git. Perhaps you want to remove the ./configure script. This is with WoeUSB 2.1.2. I also tried to regenerate the configure script in Ubuntu 16.04 and got a bunch of errors.
 (So for now I think I'll just "sed" the version into the pre-generated configure script.)

Btw, does the smudge filter work when doing local commits? Does it update the version number in the files unless there is a "checkout" action performed? I attempted doing the very same thing myself (automated versioning with git filters) just a few weeks ago, but ended up going back to "get version number as part of build" instead, because I got stale version numbers in my files.
