### ISSUE TITLE
installation failed !

### ISSUE THREAD

**Issue by anandvoyager** [slacka/WinUSB#90]
installed the build dependancies on fedora 25 , gave ./configure , below is the output.

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p,
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for g++... no
checking for c++... no
checking for gpp... no
checking for aCC... no
checking for CC... no
checking for cxx... no
checking for cc++... no
checking for cl.exe... no
checking for FCC... no
checking for KCC... no
checking for RCC... no
checking for xlC_r... no
checking for xlC... no
checking whether the C++ compiler works... no
configure: error: in `/home/papoodiya/Downloads/WinUSB-master':
configure: error: C++ compiler cannot create executables

What can i do ?

**Comment by slacka** [comment]
The error tells you exactly what's wrong. You don't have a compiler installed on your system.

`dnf install gcc-c++`
