### ISSUE TITLE
Problem with grub.cfg

### ISSUE THREAD

**Issue by shmohawk** [slacka/WinUSB#94]
Upon boot, a USB stick created from Fedora leaves you stranded at the grub shell, however `configfile (hd0,msdos1)/grub/grub.cfg` will boot the stick properly.
Fix:
```diff
diff --git a/src/winusb b/src/winusb
index f4e0ac6..1784dab 100755
--- a/src/winusb
+++ b/src/winusb
@@ -413,7 +413,14 @@ uuid=$(blkid -o value -s UUID "$partition")
 
 # grub.cfg 
 echo "Installing grub.cfg..."
-cfgFilename="$partitionMountPath/grub/grub.cfg" 
+
+if [ -d "$partitionMountPath/grub2" ]
+then
+    cfgFilename="$partitionMountPath/grub2/grub.cfg"
+else
+    cfgFilename="$partitionMountPath/grub/grub.cfg" 
+fi
+
 mkdir -p "$(dirname "$cfgFilename")"
 echo -n "" > "$cfgFilename"

```

**Comment by slacka** [comment]
@shmohawk 
Thanks. This looks good. Please submit a pull request.

**Comment by Lin-Buo-Ren** [comment]
Hello @shmohawk and others who have affected by this issue:

I've patched the code to fix the issue, please check if it is resolved by using the latest snapshot, thanks!
